import "./globals.css";
import '@fontsource/bebas-neue';
import type { Metadata } from "next";
import '@fontsource-variable/quicksand';
import '@fontsource-variable/league-spartan';

import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Centro Médico",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Header /> 
        {children}
        <Footer />
      </body>
    </html>
  );
}
